version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  speedtest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speedtest
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://root:password@mongodb:27017
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - speedtest

  flask-api:
    build:
      context: ./flask-api
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb